[project]
name = "graphs_generator"
version = "0.1.0"
description = "Generating graphs for my webpage with python."
authors = [
    { name = "Alexander Lindholm", email = "lindholmalexander.la@gmail.com" }
]
license = "MIT"
readme = "README.md"

[tool.setuptools.packages.find]
where = ["scripts"]

[project.optional-dependencies]
graphs = [
    'pandas',
    'plotly',
]

linting = [
    "flake8",
    "mypy",
    "isort",
    "pre-commit",
]

dev = [
    "pytest",
    "black",
    "isort",
    "kaleido",
]
