name: Run Spider Skills Script and Push Changes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight(00:00)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas plotly kaleido

      - name: Run Spider Skills Script
        run: python src/spider_skills.py

      - name: Commit files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/images/spider_chart.png
          git commit -m "Update spider chart via GitHub Actions"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # ${{ github.ref }}